#!/usr/bin/env python3
"""Build Audit V14 supplement tables from the verified V3.1 200-case run.

This generator reads only frozen machine-readable outputs.  It validates the
designed grid, paired mutation schedule, aggregate values, lineage equality,
artifact completeness, and independent-verifier result before writing LaTeX.
It does not execute the production validator or change any experiment result.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


METHOD_ORDER = (
    "B0_FIELD_PRESENCE",
    "B1_JSON_SCHEMA",
    "B2_MULTIPLICITY_ONLY",
    "B3_HASH_ONLY",
    "B4_ACCOUNTANT_ONLY",
    "A1_RUNTIME_ASSUMED_MATCHED",
    "A2_FULL_MINUS_VACUITY",
    "FULL",
)

METHOD_LABEL = {
    "B0_FIELD_PRESENCE": "B0 field presence",
    "B1_JSON_SCHEMA": "B1 JSON Schema",
    "B2_MULTIPLICITY_ONLY": "B2 multiplicity only",
    "B3_HASH_ONLY": "B3 hash only",
    "B4_ACCOUNTANT_ONLY": "B4 accountant only",
    "A1_RUNTIME_ASSUMED_MATCHED": "A1 runtime assumed matched",
    "A2_FULL_MINUS_VACUITY": "A2 full minus vacuity",
    "FULL": "FULL",
}

EXPECTED = {
    "B0_FIELD_PRESENCE": (100, 60, 0, 40),
    "B1_JSON_SCHEMA": (96, 60, 0, 40),
    "B2_MULTIPLICITY_ONLY": (100, 80, 0, 4),
    "B3_HASH_ONLY": (96, 60, 0, 40),
    "B4_ACCOUNTANT_ONLY": (88, 60, 0, 40),
    "A1_RUNTIME_ASSUMED_MATCHED": (12, 100, 188, 0),
    "A2_FULL_MINUS_VACUITY": (4, 100, 196, 0),
    "FULL": (0, 100, 200, 0),
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def latex(value: object) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in str(value))


def code(value: object) -> str:
    escaped = latex(value)
    escaped = escaped.replace(r"\_", r"\_\allowbreak ")
    escaped = escaped.replace("; ", r";\allowbreak ")
    return r"\texttt{" + escaped + "}"


def digest(value: object) -> str:
    return r"\seqsplit{\texttt{" + latex(value) + "}}"


def write_generated(path: Path, content: str) -> None:
    path.write_text(
        "% AUTO-GENERATED by "
        "scripts/build_validator_ablation_v3_1_supplement_tables.py.\n"
        "% Do not edit by hand; rebuild from the frozen V3.1 evidence.\n"
        + content.rstrip()
        + "\n",
        encoding="utf-8",
        newline="\n",
    )


def build_ablation(rows: list[dict[str, str]]) -> str:
    by_method = {row["method"]: row for row in rows}
    require(tuple(by_method) == METHOD_ORDER, "Unexpected aggregate method order")
    body: list[str] = []
    for method in METHOD_ORDER:
        row = by_method[method]
        observed = (
            int(row["unsafe_positives"]),
            int(row["valid_exact_decisions"]),
            int(row["exact_tuples"]),
            int(row["wrong_same_number"]),
        )
        require(
            observed == EXPECTED[method], f"Unexpected metrics for {method}: {observed}"
        )
        unsafe, valid, exact, same = observed
        label = METHOD_LABEL[method]
        if method == "FULL":
            label = r"\textbf{FULL}"
            unsafe_cell = r"\textbf{0/100 (0.00)}"
            valid_cell = r"\textbf{100/100 (1.00)}"
            exact_cell = r"\textbf{200/200 (1.00)}"
        else:
            unsafe_cell = f"{unsafe}/100 ({unsafe / 100:.2f})"
            valid_cell = f"{valid}/100 ({valid / 100:.2f})"
            exact_cell = f"{exact}/200 ({exact / 200:.2f})"
        body.append(
            " & ".join(
                [
                    label,
                    unsafe_cell,
                    valid_cell,
                    exact_cell,
                    str(same),
                    row["median_wall_ms"],
                    row["max_wall_ms"],
                ]
            )
            + r" \\"
        )
    return "\n".join(
        [
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{2.2pt}",
            r"\renewcommand{\arraystretch}{1.10}",
            r"\begin{longtable}{@{}p{.22\textwidth}p{.15\textwidth}p{.15\textwidth}p{.15\textwidth}p{.10\textwidth}p{.08\textwidth}p{.08\textwidth}@{}}",
            r"\caption{Controlled obligation projections and ablations on the designed 200-case suite. Raw fractions are deterministic case outcomes, not statistical estimates. Timing is descriptive wall-clock milliseconds.}\label{tab:supp-ablation-200}\\",
            r"\toprule",
            r"Probe / full contract & Unsafe positive & Valid exact & Exact tuple & Same-number & Median & Max \\",
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{7}{l}{\itshape Table \thetable\ continued}\\",
            r"\toprule",
            r"Probe / full contract & Unsafe positive & Valid exact & Exact tuple & Same-number & Median & Max \\",
            r"\midrule",
            r"\endhead",
            r"\midrule \multicolumn{7}{r}{\itshape Continued on next page}\\",
            r"\endfoot",
            r"\bottomrule",
            r"\endlastfoot",
            *body,
            r"\end{longtable}",
            r"\endgroup",
        ]
    )


def build_allowed_grid(allowed: list[dict[str, Any]]) -> str:
    by_cell = {
        (case["stratum_id"], int(case["level"]), case["context_id"]): case
        for case in allowed
    }
    body: list[str] = []
    for stratum_index in range(1, 6):
        stratum = f"S{stratum_index}"
        for level in range(1, 6):
            cases = [
                by_cell[(stratum, level, f"C{context}")] for context in range(1, 5)
            ]
            first = cases[0]
            evidence = (
                f"n={first['selected_record_count']}; "
                f"kappa_e={first['observed_event_kappa']}; K={first['expected_k']}"
            )
            body.append(
                " & ".join(
                    [
                        code(f"{stratum} {first['stratum_name']}"),
                        f"L{level}; {latex(evidence)}",
                        *(code(case["case_id"]) for case in cases),
                    ]
                )
                + r" \\"
            )
    return "\n".join(
        [
            r"\begingroup",
            r"\fontsize{6.4}{7.3}\selectfont",
            r"\setlength{\tabcolsep}{1.6pt}",
            r"\renewcommand{\arraystretch}{1.08}",
            r"\begin{longtable}{@{}p{.18\textwidth}p{.14\textwidth}p{.16\textwidth}p{.16\textwidth}p{.16\textwidth}p{.16\textwidth}@{}}",
            r"\caption{Complete $5\times5\times4$ allowed-case coverage matrix. C1 is canonical, C2 has irregular half-open supports, C3 adds non-selected decoy rows, and C4 permutes file order while preserving selected semantics.}\label{tab:supp-allowed-grid-200}\\",
            r"\toprule",
            r"Stratum / route & Level evidence & C1 & C2 & C3 & C4 \\",
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{6}{l}{\itshape Table \thetable\ continued}\\",
            r"\toprule",
            r"Stratum / route & Level evidence & C1 & C2 & C3 & C4 \\",
            r"\midrule",
            r"\endhead",
            r"\midrule \multicolumn{6}{r}{\itshape Continued on next page}\\",
            r"\endfoot",
            r"\bottomrule",
            r"\endlastfoot",
            *body,
            r"\end{longtable}",
            r"\endgroup",
        ]
    )


def build_operator_matrix(non_allow: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for case in non_allow:
        grouped[case["operator_id"]].append(case)
    body: list[str] = []
    for index in range(1, 26):
        operator = f"O{index:02d}"
        cases = sorted(grouped[operator], key=lambda case: case["case_id"])
        require(len(cases) == 4, f"{operator} does not have four cases")
        mutation = cases[0]["description"].split(": ", 1)[-1].rstrip(".")
        outcome = f"{cases[0]['expected_release_status']}; {cases[0]['expected_issue_code'] or 'path-only'}"
        parents = "; ".join(case["parent_case_id"] for case in cases)
        body.append(
            " & ".join([code(operator), latex(mutation), code(outcome), code(parents)])
            + r" \\"
        )
    return "\n".join(
        [
            r"\begingroup",
            r"\fontsize{6.2}{7.1}\selectfont",
            r"\setlength{\tabcolsep}{2pt}",
            r"\renewcommand{\arraystretch}{1.08}",
            r"\begin{longtable}{@{}p{.06\textwidth}p{.28\textwidth}p{.28\textwidth}p{.34\textwidth}@{}}",
            r"\caption{Complete $25\times4$ paired non-allow operator--parent matrix. Each allowed parent appears exactly once. The diagnostic shown is the predeclared primary result; documented cascades may accompany it.}\label{tab:supp-operator-grid-200}\\",
            r"\toprule",
            r"ID & Direct semantic mutation & Expected status; primary diagnostic & Four distinct allowed parents \\",
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{4}{l}{\itshape Table \thetable\ continued}\\",
            r"\toprule",
            r"ID & Direct semantic mutation & Expected status; primary diagnostic & Four distinct allowed parents \\",
            r"\midrule",
            r"\endhead",
            r"\midrule \multicolumn{4}{r}{\itshape Continued on next page}\\",
            r"\endfoot",
            r"\bottomrule",
            r"\endlastfoot",
            *body,
            r"\end{longtable}",
            r"\endgroup",
        ]
    )


def build_verification_summary() -> str:
    return "\n".join(
        [
            r"\begin{table}[t]",
            r"\centering",
            r"\small",
            r"\begin{tabular}{lr}",
            r"\hline",
            r"Surface & Passing checks \\",
            r"\hline",
            r"Contract regression & 83/83 \\",
            r"Designed controlled probes & 20,909/20,909 \\",
            r"Retrospective lineage & 176/176 \\",
            r"UCI full (each of five) & 49/49 \\",
            r"UCI portable (each of five) & 38/38 \\",
            r"UCI aggregate & 31/31 \\",
            r"\hline",
            r"\end{tabular}",
            r"\caption{Selected verification surfaces used for scale and portable-run distinctions. Table~\ref{tab:supp-verification-200} gives the complete compact inventory. Counts expose checked deterministic predicates; they are not statistical confidence.}",
            r"\label{tab:v14-verification}",
            r"\end{table}",
        ]
    )


def build_verification_detailed() -> str:
    rows = (
        (
            "Designed conformance and ablations",
            "20,909/20,909",
            "standard-library oracle and hash closure",
        ),
        ("Legacy 31-case regression", "394/394", "retained comparison surface"),
        (
            "TensorFlow Privacy scope comparison",
            "79/79",
            "official scalar statement execution",
        ),
        (
            "WISDM hardened execution",
            "38/38",
            "raw rescan--runtime--accountant--report",
        ),
        ("Sepsis mapping study", "128/128", "mapping only"),
        ("Backblaze mapping study", "86/86", "archive rescan; mapping only"),
    )
    body = [
        f"{label} & {checks} & pass & {authority} \\\\"
        for label, checks, authority in rows
    ]
    return "\n".join(
        [
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{2.5pt}",
            r"\renewcommand{\arraystretch}{1.10}",
            r"\begin{longtable}{@{}p{.34\textwidth}p{.15\textwidth}p{.10\textwidth}p{.36\textwidth}@{}}",
            r"\caption{Separately implemented verification surfaces. Counts enumerate deterministic checks, not statistical confidence or third-party operation.}\label{tab:supp-verification-200}\\",
            r"\toprule",
            r"Bundle & Checks & Result & Authority \\",
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{4}{l}{\itshape Table \thetable\ continued}\\",
            r"\toprule",
            r"Bundle & Checks & Result & Authority \\",
            r"\midrule",
            r"\endhead",
            r"\midrule \multicolumn{4}{r}{\itshape Continued on next page}\\",
            r"\endfoot",
            r"\bottomrule",
            r"\endlastfoot",
            *body,
            r"\end{longtable}",
            r"\endgroup",
        ]
    )


def build_artifact_inputs(paths: dict[str, Path], repo_root: Path) -> str:
    body = []
    for name, path in sorted(paths.items()):
        relative = path.relative_to(repo_root).as_posix()
        body.append(
            f"{latex(name)}: \\path{{{relative}}} & {digest(sha256_file(path))} \\\\"
        )
    return "\n".join(
        [
            r"\begingroup",
            r"\fontsize{6.3}{7.2}\selectfont",
            r"\setlength{\tabcolsep}{2pt}",
            r"\begin{longtable}{@{}p{.55\textwidth}p{.41\textwidth}@{}}",
            r"\caption{Claim-bearing inputs for the designed 200-case table. The verification index separately binds the artifact index, verifier source, and verification result.}\label{tab:supp-ablation-inputs-200}\\",
            r"\toprule",
            r"Repository-relative input & SHA-256 \\",
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{2}{l}{\itshape Table \thetable\ continued}\\",
            r"\toprule Repository-relative input & SHA-256 \\",
            r"\midrule",
            r"\endhead",
            r"\bottomrule",
            r"\endfoot",
            *body,
            r"\end{longtable}",
            r"\endgroup",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root", type=Path, default=Path(__file__).resolve().parents[1]
    )
    parser.add_argument("--paper-root", type=Path, default=None)
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    paper_root = (
        args.paper_root.resolve()
        if args.paper_root
        else (
            repo_root.parent / "AAAI27_7p_compressed" / "01_audit_reporting_paper"
        ).resolve()
    )
    report_root = repo_root / "reports/validator_ablation_v3_1_200_001"
    output_root = paper_root / "supplement_v14_generated"
    output_root.mkdir(parents=True, exist_ok=True)

    paths = {
        "frozen protocol": repo_root
        / "paper_notes/AAAI27_AUDIT_V19_CONFORMANCE_200_PROTOCOL_V1_2026-07-28.md",
        "runner": repo_root / "scripts/run_validator_ablation_v3_1.py",
        "verifier": repo_root / "scripts/verify_validator_ablation_v3_2.py",
        "cases": report_root / "cases.json",
        "aggregate metrics": report_root / "aggregate_metrics.csv",
        "input lineage": report_root / "v3_input_lineage_equivalence.json",
        "execution status": report_root / "execution_status.json",
        "artifact index": report_root / "artifact_index.json",
        "independent verification": report_root / "independent_verification.json",
        "verification index": report_root / "verification_index.json",
    }
    for name, path in paths.items():
        require(path.is_file(), f"Missing {name}: {path}")

    cases_payload = load_json(paths["cases"])
    cases = cases_payload["cases"]
    allowed = [case for case in cases if case["case_kind"] == "allowed"]
    non_allow = [case for case in cases if case["case_kind"] == "non_allow"]
    require(
        len(cases) == 200 and len(allowed) == 100 and len(non_allow) == 100,
        "Case counts changed",
    )
    require(
        Counter(case["stratum_id"] for case in allowed)
        == {f"S{i}": 20 for i in range(1, 6)},
        "Allowed stratum coverage changed",
    )
    require(
        Counter(case["context_id"] for case in allowed)
        == {f"C{i}": 25 for i in range(1, 5)},
        "Allowed context coverage changed",
    )
    require(
        len({case["case_id"] for case in cases}) == 200,
        "Case identifiers are not unique",
    )
    require(
        len({case["input_triple_sha256"] for case in cases}) == 200,
        "Input triples are not unique",
    )
    require(
        len({case["parent_case_id"] for case in non_allow}) == 100,
        "Parent schedule is not one-to-one",
    )
    require(
        Counter(case["operator_id"] for case in non_allow)
        == {f"O{i:02d}": 4 for i in range(1, 26)},
        "Operator schedule changed",
    )

    full_mapping_hashes: set[str] = set()
    selected_mapping_hashes: set[str] = set()
    for case in allowed:
        report = load_json(repo_root / case["report_path"])
        full_mapping_hashes.add(report["pipeline"]["mapping_file_sha256"])
        selected_mapping_hashes.add(report["pipeline"]["selected_mapping_sha256"])
    require(
        len(full_mapping_hashes) == 100, "Expected 100 distinct full mapping hashes"
    )
    require(
        len(selected_mapping_hashes) == 50,
        "Expected 50 selected-semantic mapping hashes",
    )

    execution = load_json(paths["execution status"])
    require(
        execution["gates_passed"] is True
        and execution["v3_input_content_equal"] is True,
        "Runner gates failed",
    )
    lineage = load_json(paths["input lineage"])
    require(lineage["all_200_input_content_equal"] is True, "V3 input lineage mismatch")
    require(
        lineage["all_200_oracle_metadata_equal"] is True, "V3 oracle lineage mismatch"
    )
    require(len(lineage["cases"]) == 200, "Lineage case count changed")

    verification = load_json(paths["independent verification"])
    require(verification["passed"] is True, "Independent verification failed")
    require(
        verification["check_count"] == 20909 and verification["failure_count"] == 0,
        "Verification counts changed",
    )
    require(
        verification["standard_library_only"] is True,
        "Verifier import boundary changed",
    )
    require(
        verification["independent_grid_operator_oracle"] is True,
        "Independent oracle missing",
    )
    require(
        verification["internal_registry_hash_closure"] is True,
        "Registry hash closure missing",
    )

    artifact_index = load_json(paths["artifact index"])
    require(len(artifact_index["files"]) == 627, "Artifact-index count changed")
    require(
        sum("/case_inputs/" in item["path"] for item in artifact_index["files"]) == 600,
        "Raw case-input count changed",
    )

    aggregate = load_csv(paths["aggregate metrics"])
    outputs = {
        "ablation_metrics.tex": build_ablation(aggregate),
        "allowed_grid.tex": build_allowed_grid(allowed),
        "operator_matrix.tex": build_operator_matrix(non_allow),
        "verification_surface_summary.tex": build_verification_summary(),
        "verification_surface_detailed.tex": build_verification_detailed(),
        "artifact_inputs.tex": build_artifact_inputs(paths, repo_root),
    }
    for filename, content in outputs.items():
        write_generated(output_root / filename, content)

    generator_path = Path(__file__).resolve()
    manifest = {
        "schema_version": "audit_validator_ablation_v3_1_supplement_tables_v1.0",
        "generator": {
            "path": generator_path.relative_to(repo_root).as_posix(),
            "sha256": sha256_file(generator_path),
        },
        "counts": {
            "allowed_cases": 100,
            "non_allow_cases": 100,
            "operators": 25,
            "full_mapping_hashes": len(full_mapping_hashes),
            "selected_semantic_mapping_hashes": len(selected_mapping_hashes),
            "artifact_index_files": len(artifact_index["files"]),
            "raw_case_input_files": 600,
            "independent_checks": verification["check_count"],
        },
        "inputs": {
            name: {
                "path": path.relative_to(repo_root).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": sha256_file(path),
            }
            for name, path in sorted(paths.items())
        },
        "outputs": {
            filename: {
                "path": (output_root / filename).relative_to(paper_root).as_posix(),
                "bytes": (output_root / filename).stat().st_size,
                "sha256": sha256_file(output_root / filename),
            }
            for filename in sorted(outputs)
        },
    }
    provenance_path = output_root / "provenance.json"
    provenance_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(
        json.dumps(
            {
                "status": "PASS",
                "output_root": str(output_root),
                "outputs": len(outputs),
                "allowed": len(allowed),
                "non_allow": len(non_allow),
                "independent_checks": verification["check_count"],
                "provenance_sha256": sha256_file(provenance_path),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
