[package]
name = "zk-genguard-methods"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
risc0-zkvm = { version = "3.0.4", default-features = false }
zk-genguard-common = { path = "../common" }

[build-dependencies]
risc0-build = "3.0.4"

[package.metadata.risc0]
methods = ["guest"]
